export const testData =
    [
        {
            "_id": "5d0b4aa98ed81c7d37ce55c4",
            "subject": "do laborum",
            "from":"aws.service@amazon.com",
            "body": "deserunt exercitation minim do eiusmod sit officia minim aliqua voluptate aute sunt laborum adipisicing amet aliquip anim culpa non adipisicing ullamco tempor exercitation exercitation sit quis consequat ullamco sint tempor fugiat irure reprehenderit Lorem pariatur incididunt irure fugiat ipsum eiusmod et ipsum non mollit tempor amet aliqua esse Lorem qui occaecat magna mollit aliqua adipisicing qui officia reprehenderit nulla cupidatat proident ipsum occaecat reprehenderit enim ullamco et ad do dolor ea officia do reprehenderit consectetur ullamco sit deserunt velit labore non excepteur nisi non eiusmod velit eiusmod nulla veniam culpa do excepteur Lorem cupidatat aliquip proident minim mollit duis irure",
            "isRead": false,
            "sentAt": "Fri Jul 13 2018 02:17:55 GMT+0300 (Israel Daylight Time)",
            "isFavorite": false,
            "isDeleted": false,
        },
        {
            "_id": "5d0b4aa9a0adb4a2e6e022b4",
            "subject": "sign in notification",
            "from":"info@google.com",
            "body": "fugiat fugiat veniam enim non Lorem nulla consequat commodo laboris sint nulla tempor non Lorem pariatur ea exercitation mollit qui aute velit excepteur voluptate non sunt aliquip consectetur incididunt et est enim laborum consectetur aliquip nisi commodo ad in velit fugiat exercitation ad consequat laborum ipsum proident ea occaecat exercitation consequat eiusmod aliqua pariatur mollit anim eiusmod nisi duis qui anim ad veniam non veniam minim commodo cupidatat culpa ea excepteur velit veniam consectetur esse aliquip dolor consectetur enim aute est nulla cillum deserunt ea in id cupidatat do ipsum elit Lorem pariatur nulla id adipisicing excepteur et sit eiusmod",
            "isRead": true,
            "sentAt": "Fri Feb 07 2014 14:17:31 GMT+0200 (Israel Standard Time)",
            "isFavorite": false,
            "isDeleted": false,
        },
        {
            "_id": "5d0b4aa9f84200e7f26f378f",
            "subject": "reprehenderit labore",
            "from":"info@google.com",
            "body": "amet quis sunt esse dolore incididunt sunt est sint velit non duis cupidatat laboris officia quis non sit consectetur irure officia quis minim fugiat ullamco tempor enim est fugiat aliqua irure quis ex amet labore esse id et ullamco ullamco exercitation elit ad in aliquip ut commodo in reprehenderit id elit fugiat ex aliquip quis ad Lorem enim sit in magna aute consequat exercitation anim sit magna eiusmod et cupidatat nulla adipisicing minim nostrud cupidatat Lorem laboris incididunt ea aliqua dolor voluptate excepteur anim minim aliquip cillum esse labore Lorem in velit voluptate amet laborum irure exercitation voluptate duis veniam",
            "isRead": false,
            "sentAt": "Fri Jul 01 2016 23:33:50 GMT+0300 (Israel Daylight Time)",
            "isFavorite": false,
            "isDeleted": false,
        },
        {
            "_id": "5d0b4aa9c33b427d05d6920f",
            "subject": "id Lorem",
            "from":"info@google.com",
            "body": "non voluptate in sint et consequat aliquip cupidatat cillum velit deserunt sint sit dolor reprehenderit exercitation nisi officia do nisi nostrud qui pariatur dolor ad non deserunt consectetur aliquip pariatur officia elit adipisicing Lorem nostrud incididunt Lorem voluptate elit qui laborum est culpa ipsum excepteur enim culpa elit eu elit veniam esse exercitation elit enim qui aliquip consequat esse irure anim aute cupidatat aliqua culpa non consequat cillum laboris enim sunt culpa ipsum esse aute irure duis magna nostrud consequat culpa Lorem enim ut ea veniam ut pariatur dolor voluptate velit labore reprehenderit incididunt qui sint proident ipsum ut commodo",
            "isRead": true,
            "sentAt": "Mon May 09 2016 17:00:58 GMT+0300 (Israel Daylight Time)",
            "isFavorite": false,
            "isDeleted": false,
        },
        {
            "_id": "5d0b4aa9f1a0f57e122ecde8",
            "subject": "ex ea",
            "from":"info@google.com",
            "body": "ipsum do eiusmod labore irure deserunt ea nulla aliqua et officia elit aliqua ad cillum reprehenderit occaecat reprehenderit cupidatat nisi quis dolor aliquip nostrud elit mollit nisi non qui ex incididunt nulla nulla ad voluptate ullamco duis laboris consectetur culpa mollit voluptate nostrud aute id voluptate magna proident dolor enim duis consectetur fugiat qui aliquip ea amet excepteur tempor deserunt pariatur proident esse laborum et commodo dolor nostrud consectetur consectetur sunt aute minim sunt occaecat duis eiusmod dolore labore eiusmod adipisicing elit do esse elit incididunt consectetur aute commodo commodo exercitation in ad aliquip in eu anim pariatur est anim",
            "isRead": false,
            "sentAt": "Thu Aug 09 2018 22:21:01 GMT+0300 (Israel Daylight Time)",
            "isFavorite": false,
            "isDeleted": false,
        },
        {
            "_id": "5d0b4aa97e297a2584756bdd",
            "subject": "consectetur elit",
            "from":"info@google.com",
            "body": "irure do occaecat mollit magna quis proident Lorem do consequat eu labore fugiat Lorem minim esse cupidatat minim est duis esse nostrud cillum anim ullamco minim est adipisicing ea in ex incididunt sit adipisicing id sint aute proident nisi laboris duis incididunt nisi proident ut nulla aliqua nisi laborum proident amet nostrud magna ea consequat irure excepteur ullamco pariatur nostrud exercitation dolore laboris exercitation id commodo exercitation amet sit ut pariatur deserunt incididunt nisi magna occaecat deserunt incididunt est culpa sunt in qui fugiat ut irure deserunt nisi commodo fugiat ex commodo sint amet velit officia voluptate mollit proident esse",
            "isRead": true,
            "sentAt": "Fri Dec 14 2018 04:17:58 GMT+0200 (Israel Standard Time)",
            "isFavorite": false,
            "isDeleted": false,
        }
    ]